### ISSUE TITLE
example script(thulac.py) SEGFAULT with missing DAT file(models/vM.dat)

### ISSUE THREAD

**Issue by plumex** [thunlp/THULAC.so#1]
hello THUNLP team, I got some weird error when running example file, the error msg output below: 

 `» python thulac.py`
`[ERROR] DAT file /Users/plumex/Downloads/source/THULAC.So/models/vM.dat not found`
`[1]    91927 segmentation fault  python thulac.py`

it's seem .so file try to open the vM.dat file, but can not find this file inside lastest Models_v1_v2.zip package

if I missed anything information pls help.

**Comment by gzp9595** [comment]
Thank you for your support for THULAC, we have fixed this bug. You can git the new version to use it~
